### ISSUE TITLE
Mechanism for callback when using Swipeback

### ISSUE THREAD

**Issue by keyboardsamurai** [devxoul/SwipeBack#12]
Sorry if I missed something, but Is there any way I can get notified when Swipeback is used? Like a callback? Sometimes you have to perform some internal bookeeping when navigating through screens. This would be super handy.

**Comment by keyboardsamurai** [comment]
Sorry for the late answer. I guess `viewWillDisappear`could work in some use cases. 

But for example when I have a situation where I want to warn the user when he is about to lose state when he leaves the screen, I want to explicitly get a callback before swiping is started so I can interrupt the swipe action.

**Comment by devxoul** [comment]
I think you can use [`UIScreenEdgePanGestureRecognizer`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIScreenEdgePanGestureRecognizer_class/) to do that.
