### ISSUE TITLE
Swipe on RootViewController

### ISSUE THREAD

**Issue by gotokatsuya** [devxoul/SwipeBack#3]
Hi @devxoul .

My App was stopped when I swiped on RootViewController, then pushed to next controller.

Do you know what this is ?

Thank you.

**Comment by devxoul** [comment]
Awesome, I already knew that my app sometimes got freezed, but it has never been reproduced when I tried. It was a root view controller!

I'll take a look and make a patch ASAP.

Thank you for you report!!!

**Comment by devxoul** [comment]
@gotokatsuya, I just released 1.0.5! If the problem still exists, tell me.
Thank you again :)

**Comment by gotokatsuya** [comment]
@devxoul

 Thank you so much. I will try.

**Comment by gotokatsuya** [comment]
@devxoul 

This is my code. Is this wrong ?
```
override func viewWillAppear(animated: Bool) {
    super.viewWillAppear(animated)
    self.navigationController?.swipeBackEnabled = true        
}
```

When I deleted ``` self.navigationController?.swipeBackEnabled = true```, My app was not stopped.

**Comment by devxoul** [comment]
@gotokatsuya, What did you intend?

**Comment by gotokatsuya** [comment]
@devxoul I have two story.

・The First time
``` FirstContoller(ROOT) - TutorialController - MainController - TableController```

I don't want users to swipe on TutorialController and MainController.
I want users to swipe on TableController.


・From The Second time
``` MainController(ROOT)  - TableController```

I want users to swipe on TableController. 

Thank you.

**Comment by devxoul** [comment]
Set `self.navigationController?.swipeBackEnabled = false` on **TutorialController** and **MainController**'s `viewWillAppear:` method. Then you can set `self.navigationController?.swipeBackEnabled = true` on TableController's `viewWillAppear:`.

Is that related to freezing issue?

**Comment by gotokatsuya** [comment]
@devxoul Yes it is. 

I set like you said. When I swiped on **TableController**, My app was stopped..


I am grateful for all your help. You are a grate developer.

**Comment by devxoul** [comment]
Oh, I got it. I'll fix it soon. Thanks!

**Comment by gotokatsuya** [comment]
Thank you so much!

**Comment by devxoul** [comment]
@gotokatsuya, sorry for delay. I just make a new release. Could you please try with 1.0.6? Thanks :)

**Comment by gotokatsuya** [comment]
@devxoul No problem. 

Greate:) Thank you soo much!

**Comment by devxoul** [comment]
:beer::+1:
