### ISSUE TITLE
Now working iPad with iPhone UI

### ISSUE THREAD

**Issue by primoz990** [devxoul/SwipeBack#8]
I'm developing an app with iPhone only userinterface. When i run the app on an iPad with iOS 8, the app is presented like this: http://i.stack.imgur.com/HH9ad.png  you know what i mean...
The SwipeBack action is not working in this case.

Otherwise the SwipeBack is working great on iPhone. Thanks ;)

**Comment by devxoul** [comment]
@primoz990, iPad originally doesn't support swipe-to-back feature for iPhone only apps.

**Comment by primoz990** [comment]
Oh..., didn't know that... well then, thats not an issue i guess. 
My bad. Sorry.

**Comment by devxoul** [comment]
It's okay. I had same question when I developed SwipeBack and tested on my iPad. :smile:
